# Generated by Django 3.1.5 on 2021-04-09 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DocSource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_name', models.CharField(max_length=100)),
                ('source_link', models.CharField(max_length=200)),
                ('soucer_description', models.CharField(max_length=1000)),
                ('source_type', models.CharField(choices=[('Gitlab', 'Gitlab'), ('Github', 'Github'), ('ReadTheDocs', 'ReadTheDocs'), ('Other', 'Other')], max_length=50)),
                ('pub_date', models.DateField(verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='SnippetCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snippet_code_name', models.CharField(max_length=100)),
                ('snippet_code', models.TextField(max_length=10000)),
                ('snippet_code_type', models.CharField(choices=[('openEO', 'openEO'), ('InfluxDB', 'InfluxDB'), ('python', 'python'), ('Java', 'Java')], max_length=50)),
            ],
        ),
    ]
