# Generated by Django 4.0.dev20210414102347 on 2021-04-22 09:12

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeonetworkMetadata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('abstract', models.TextField(max_length=10000)),
                ('category', models.CharField(max_length=100)),
                ('keyword', models.CharField(max_length=500)),
                ('image', models.CharField(max_length=500)),
                ('geom', django.contrib.gis.db.models.fields.PolygonField(srid=4326)),
            ],
        ),
    ]
