# Generated by Django 3.1.5 on 2021-02-15 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docsource',
            name='pub_date',
            field=models.DateField(verbose_name='date published'),
        ),
    ]
