# Generated by Django 3.1.5 on 2021-02-15 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0002_auto_20210215_1913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docsource',
            name='source_type',
            field=models.CharField(choices=[('GL', 'Gitlab'), ('GH', 'Github'), ('RTD', 'ReadTheDocs'), ('O', 'Other')], max_length=50),
        ),
    ]
