# Generated by Django 4.0.dev20210414102347 on 2021-04-22 16:00

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0002_geonetworkmetadata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geonetworkmetadata',
            name='abstract',
            field=models.TextField(max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='geonetworkmetadata',
            name='category',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='geonetworkmetadata',
            name='geom',
            field=django.contrib.gis.db.models.fields.PolygonField(null=True, srid=4326),
        ),
        migrations.AlterField(
            model_name='geonetworkmetadata',
            name='image',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='geonetworkmetadata',
            name='keyword',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='geonetworkmetadata',
            name='title',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
