# Generated by Django 4.0.dev20210414102347 on 2021-04-22 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0003_alter_geonetworkmetadata_abstract_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='geonetworkmetadata',
            old_name='image',
            new_name='thumbnail',
        ),
        migrations.AlterField(
            model_name='geonetworkmetadata',
            name='uuid',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
