# Generated by Django 3.1.5 on 2021-02-15 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0003_auto_20210215_1924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docsource',
            name='source_type',
            field=models.CharField(choices=[('Gitlab', 'Gitlab'), ('Github', 'Github'), ('ReadTheDocs', 'ReadTheDocs'), ('Other', 'Other')], max_length=50),
        ),
    ]
