# Generated by Django 4.0.dev20210414102347 on 2021-04-23 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0004_rename_image_geonetworkmetadata_thumbnail_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geonetworkmetadata',
            name='thumbnail',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
