# Generated by Django 3.1.5 on 2021-03-03 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0004_auto_20210215_1926'),
    ]

    operations = [
        migrations.CreateModel(
            name='SourceCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_name', models.CharField(max_length=100)),
                ('source_code', models.CharField(max_length=10000)),
                ('code_type', models.CharField(choices=[('Gitlab', 'Gitlab'), ('Github', 'Github'), ('ReadTheDocs', 'ReadTheDocs'), ('Other', 'Other')], max_length=50)),
            ],
        ),
    ]
