# Generated by Django 3.1.5 on 2021-03-03 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0005_sourcecode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sourcecode',
            name='code_type',
            field=models.CharField(choices=[('openEO', 'openEO'), ('InfluxDB', 'InfluxDB'), ('python', 'python'), ('Java', 'Java')], max_length=50),
        ),
    ]
