# Generated by Django 3.1.5 on 2021-03-03 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0006_auto_20210303_1836'),
    ]

    operations = [
        migrations.CreateModel(
            name='SnippetCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snippet_code_name', models.CharField(max_length=100)),
                ('snippet_code', models.CharField(max_length=10000)),
                ('snippet_code_type', models.CharField(choices=[('openEO', 'openEO'), ('InfluxDB', 'InfluxDB'), ('python', 'python'), ('Java', 'Java')], max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='SourceCode',
        ),
    ]
