# Generated by Django 4.0.dev20210414102347 on 2021-04-23 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0006_alter_geonetworkmetadata_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geonetworkmetadata',
            name='thumbnail',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
