# Generated by Django 3.1.5 on 2021-03-03 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0007_auto_20210303_1839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snippetcode',
            name='snippet_code',
            field=models.TextField(max_length=10000),
        ),
    ]
