# Generated by Django 4.0.dev20210414102347 on 2021-04-23 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0007_alter_geonetworkmetadata_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='geonetworkmetadata',
            name='last_update',
            field=models.DateField(null=True, verbose_name='Date'),
        ),
    ]
