# Generated by Django 3.1.5 on 2021-03-10 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0008_auto_20210303_1841'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='snippetcode',
            name='id',
        ),
        migrations.AddField(
            model_name='snippetcode',
            name='auto_snippet_code_id',
            field=models.AutoField(default='', primary_key=True, serialize=False),
        ),
    ]
