# Generated by Django 4.0.dev20210414102347 on 2021-04-23 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0008_geonetworkmetadata_last_update'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geonetworkmetadata',
            name='last_update',
            field=models.DateTimeField(editable=False, null=True),
        ),
    ]
