# Generated by Django 3.1.5 on 2021-03-10 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0009_auto_20210310_1632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snippetcode',
            name='auto_snippet_code_id',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
        ),
    ]
