# Generated by Django 4.0.dev20210414102347 on 2021-04-23 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0009_alter_geonetworkmetadata_last_update'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geonetworkmetadata',
            name='category',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='geonetworkmetadata',
            name='keyword',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='geonetworkmetadata',
            name='thumbnail',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='geonetworkmetadata',
            name='title',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='geonetworkmetadata',
            name='uuid',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
