# Generated by Django 4.0.dev20210414102347 on 2021-04-28 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0010_alter_geonetworkmetadata_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='docsource',
            name='source_category',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='snippetcode',
            name='snippet_category',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='docsource',
            name='soucer_description',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='docsource',
            name='source_link',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='docsource',
            name='source_type',
            field=models.CharField(choices=[('Gitlab', 'Gitlab'), ('Github', 'Github'), ('ReadTheDocs', 'ReadTheDocs'), ('Other', 'Other')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='geonetworkmetadata',
            name='title',
            field=models.CharField(default='No title', max_length=500),
        ),
        migrations.AlterField(
            model_name='snippetcode',
            name='snippet_code',
            field=models.TextField(max_length=10000, null=True),
        ),
    ]
