# Generated by Django 4.0.dev20210414102347 on 2021-04-28 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0011_docsource_source_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='docsource',
            name='source_type',
        ),
        migrations.RemoveField(
            model_name='snippetcode',
            name='snippet_code_type',
        ),
    ]
