# Generated by Django 4.0.dev20210414102347 on 2021-04-28 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0012_remove_docsource_source_type_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='docsource',
            old_name='soucer_description',
            new_name='source_description',
        ),
    ]
