# Generated by Django 4.0.dev20210414102347 on 2021-04-28 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0013_rename_soucer_description_docsource_source_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snippetcode',
            name='snippet_category',
            field=models.CharField(default='No category', max_length=200),
        ),
    ]
