# Generated by Django 4.0.dev20210414102347 on 2021-04-28 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0014_alter_snippetcode_snippet_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geonetworkmetadata',
            name='title',
            field=models.CharField(default='No title', max_length=500, null=True),
        ),
    ]
