# Generated by Django 4.0.dev20210414102347 on 2021-05-12 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0017_alter_geonetworkmetadata_tempextentbegin_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='geonetworkmetadata',
            name='tempExtentBegin',
        ),
        migrations.RemoveField(
            model_name='geonetworkmetadata',
            name='tempExtentEnd',
        ),
    ]
