# Generated by Django 4.0.dev20210414102347 on 2021-05-12 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0018_remove_geonetworkmetadata_tempextentbegin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='geonetworkmetadata',
            name='tempExtentBegin',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='geonetworkmetadata',
            name='tempExtentEnd',
            field=models.DateTimeField(null=True),
        ),
    ]
