# Generated by Django 4.0.dev20210414102347 on 2021-05-12 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0019_geonetworkmetadata_tempextentbegin_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='geonetworkmetadata',
            name='tempExtentBegin',
        ),
        migrations.RemoveField(
            model_name='geonetworkmetadata',
            name='tempExtentEnd',
        ),
        migrations.AddField(
            model_name='geonetworkmetadata',
            name='period_begin',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='geonetworkmetadata',
            name='period_end',
            field=models.DateTimeField(null=True),
        ),
    ]
