# Generated by Django 4.0.dev20210414102347 on 2021-05-18 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0020_remove_geonetworkmetadata_tempextentbegin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='snippetcode',
            name='snippet_programming_language',
            field=models.CharField(default='No programmin language', max_length=200),
        ),
    ]
