# Generated by Django 4.0.dev20210414102347 on 2021-05-18 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0021_snippetcode_snippet_programming_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snippetcode',
            name='snippet_programming_language',
            field=models.CharField(default='No programming language', max_length=200),
        ),
    ]
