# Generated by Django 4.0.dev20210414102347 on 2022-03-18 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0022_alter_snippetcode_snippet_programming_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geonetworkmetadata',
            name='keyword',
            field=models.CharField(max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='geonetworkmetadata',
            name='thumbnail',
            field=models.CharField(max_length=5000, null=True),
        ),
    ]
