# Generated by Django 4.0.dev20210414102347 on 2022-03-18 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0023_alter_geonetworkmetadata_keyword_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geonetworkmetadata',
            name='keyword',
            field=models.CharField(max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='geonetworkmetadata',
            name='thumbnail',
            field=models.CharField(max_length=10000, null=True),
        ),
    ]
