# Generated by Django 2.2.12 on 2023-01-10 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0025_alter_geonetworkmetadata_keyword_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='geonetworkmetadata',
            name='doi',
            field=models.TextField(max_length=10000, null=True),
        ),
    ]
