# Generated by Django 2.2.12 on 2023-01-10 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0026_geonetworkmetadata_doi'),
    ]

    operations = [
        migrations.AddField(
            model_name='geonetworkmetadata',
            name='citation',
            field=models.TextField(max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='geonetworkmetadata',
            name='doi',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
