# Generated by Django 2.2.12 on 2023-03-08 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0027_auto_20230110_1251'),
    ]

    operations = [
        migrations.AddField(
            model_name='geonetworkmetadata',
            name='supplemental_information',
            field=models.TextField(max_length=10000, null=True),
        ),
    ]
