# Generated by Django 2.2.12 on 2023-10-20 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0028_geonetworkmetadata_supplemental_information'),
    ]

    operations = [
        migrations.AddField(
            model_name='geonetworkmetadata',
            name='name_collection',
            field=models.TextField(max_length=10000, null=True),
        ),
    ]
