# Generated by Django 2.2.12 on 2023-10-23 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0029_geonetworkmetadata_name_collection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geonetworkmetadata',
            name='name_collection',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
