# Generated by Django 2.2.12 on 2023-10-31 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0030_auto_20231023_1017'),
    ]

    operations = [
        migrations.AddField(
            model_name='geonetworkmetadata',
            name='cl_topic',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='geonetworkmetadata',
            name='presentationForm',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
