# Generated by Django 2.2.12 on 2023-10-31 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0031_auto_20231031_1213'),
    ]

    operations = [
        migrations.RenameField(
            model_name='geonetworkmetadata',
            old_name='presentationForm',
            new_name='presentation_form',
        ),
    ]
